name: GHSCD 2024

on: workflow_dispatch

jobs:
  hello-world:
    runs-on: ubuntu-latest
    name: Job
    steps:
      - run: id
      - run: uname -a
      - run: env
      - run: echo "Hello FEBRABAN Cyberlab!"

